work_dir: ./work_dir/NTU-RGB-D/xview/TCN

# feeder
feeder: st_gcn.feeder.Feeder
feeder_args:
  # debug: True
  random_shift: False
  random_choose: False
  window_size: 300
  data_path: ./data/NTU-RGB-D/gendata_test/xview

# model
model: st_gcn.net.TCN
model_args:
  num_class: 60
  channel: 150
  window_size: 300
  use_data_bn: True

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [30, 70]

# training
device: 0
# parallel_device: [0, 1]
batch_size: 512
test_batch_size: 512
num_epoch: 80
nesterov: True
