work_dir: ./work_dir/NTU-RGB-D/xview/TCN_GCN

# feeder
feeder: st_gcn.feeder.Feeder
feeder_args:
  # debug: True
  random_shift: False
  random_choose: False
  window_size: 300
  data_path: ./data/NTU-RGB-D/xview

# model
model: st_gcn.net.TCN_GCN
model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [50, 70]

# training
device: 0
parallel_device: [0, 1, 2, 3, 4, 5, 6, 7]
batch_size: 128
test_batch_size: 128
num_epoch: 80
nesterov: True



